
euler:
	clang Token.h Lexer.c Codebuffer.c ConstantBuffer.c Hashmap.c Parser.c Debug.c VM.c main.c && ./a.out

test:
	clang Token.h Lexer.c Codebuffer.c ConstantBuffer.c Hashmap.c Parser.c Debug.c VM.c testing/utest.h testing/main.c && ./a.out

clean:
	rm a.out
